### ISSUE TITLE
ReadMe里面N=4的描述错误

### ISSUE THREAD

**Issue by M1sury** [zjcscut/octopus#3]
![image](https://user-images.githubusercontent.com/64764195/183276457-f51d9d3c-3d5d-42e2-bf35-b982d5470baa.png)
![image](https://user-images.githubusercontent.com/64764195/183276466-3cf6e06b-3452-4604-9ff1-a2b485d6e989.png)
应该是1477w

**Comment by zjcscut** [comment]
应该是我看漏了一位，有空改一下，THX
